# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-08 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='date_publish',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间'),
        ),
    ]
